spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?createDatabaseIfNotExist=true&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: book

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - hystrix.stream
feign:
  hystrix:
    enabled: true
